### ISSUE TITLE
SCRIPT5007: Function.prototype.apply: argument is null or undefined 

### ISSUE THREAD

**Issue by roboncode** [doug-martin/declare.js#1]
Tested on IE 8
SCRIPT5007: Function.prototype.apply: argument is null or undefined 
declare.js, line 533 character 25

Fix: ln 533 - return m.apply(this, args || []);

There may be others like this, I only found this issue so far.

**Comment by doug-martin** [comment]
Can you provide a code snippet of your class?

**Comment by doug-martin** [comment]
I just pushed up changes that should address this issue. 

I will leave this ticket open until you let me know this fixes the issue.

-Doug

**Comment by roboncode** [comment]
Thanks, I don't have a simple example right now, but i will see if I can
provide one later. Rob
